# ===============================
# = Application
# ===============================
spring.application.name=torneo

# ===============================
# = Web server
# ===============================
server.port=8081

# ===============================
# = Datasource PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/torneo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / Hibernate
# ===============================
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# = Thymeleaf
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html